---
title: "WorldClim data analysis"
author: "Carlos Dobler"
date: "October 17, 2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      out.width = "90%",
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 7.5, 
                      fig.asp = 0.4, 
                      dpi = 150)


library(tidyverse)
library(stars)

# constants
x_min <- 3150L
y_min <- 2182L
x_count <- 16L
y_count <- 20L

biovars <- c(
    "Δ Annual Mean Temperature",
    "Δ Mean Diurnal Range",
    "Δ Isothermality",
    "Δ Temperature Seasonality",
    "Δ Max Temperature of Warmest Month",
    "Δ Min Temperature of Coldest Month",
    "Δ Temperature Annual Range",
    "Δ Mean Temperature of Wettest Quarter",
    "Δ Mean Temperature of Driest Quarter",
    "Δ Mean Temperature of Warmest Quarter",
    "Δ Mean Temperature of Coldest Quarter",
    "Δ Annual Precipitation",
    "Δ Precipitation of Wettest Month",
    "Δ Precipitation of Driest Month",
    "Δ Precipitation Seasonality (Coefficient of Variation)",
    "Δ Precipitation of Wettest Quarter",
    "Δ Precipitation of Driest Quarter",
    "Δ Precipitation of Warmest Quarter",
    "Δ Precipitation of Coldest Quarter")

models <- c("BCC-CSM2-MR",
            "CNRM-CM6-1",
            "CNRM-ESM2-1",
            "CanESM5",
            "IPSL-CM6A-LR",
            "MIROC-ES2L",
            "MIROC6")#,
            #"MRI-ESM2-0")

read_sf("data/belem.gpkg") -> belem

# hist
tibble(file = list.files("data/Link to WorldClim/historical_1970_2000/", full.names = T),
       v = file %>% 
           str_sub(-6) %>% 
           str_replace("_", "") %>% 
           str_sub(end = -5) %>% 
           as.numeric()) %>% 
    
    arrange(v) %>% 
    pull(file) %>% 
    
    map(~read_stars(.x, RasterIO = list(nXOff = x_min,
                                   nYOff = y_min,
                                   nXSize = x_count,
                                   nYSize = y_count))) %>% 
    do.call(c, .) %>%
    merge() %>% 
    st_set_dimensions(3, biovars) %>% 
    setNames("p_1970_2000") -> miau_c1

# future
seq_along(models) %>% 
    map(function(m){
        
        list.files("data/Link to WorldClim/future_2021_2100_ssp585/", full.names = T) %>%
            .[str_detect(., "tif")] %>% 
            .[str_detect(., models[m])] %>% 
            
            map(~read_stars(.x, RasterIO = list(nXOff = x_min,
                                                nYOff = y_min,
                                                nXSize = x_count,
                                                nYSize = y_count)) %>% 
                    st_as_stars()) %>% 
            do.call(c, .) %>% 
            st_set_dimensions("band", names = "attributes", values = biovars) %>% 
            setNames(c("p_2020_2040", "p_2040_2060", "p_2060_2080", "p_2080_2100"))
            
    }) -> miau_c2





# db %>% slice(attributes, 1) %>% select(1) %>% {ggplot() + geom_stars(data = .) + geom_sf(data = belem)}

func_plot <- function(i)
{
    
    seq_along(models) %>%
        map(function(m){
            
            db <- c(miau_c1, miau_c2[[m]])
            
            db %>% 
                slice(attributes, i) %>% 
                mutate(a = p_2020_2040 - p_1970_2000,
                       b = p_2040_2060 - p_1970_2000,
                       c = p_2060_2080 - p_1970_2000,
                       d = p_2080_2100 - p_1970_2000) %>% 
                select(a:d) %>% 
                merge() %>% 
                st_set_dimensions("attributes", c("1970-2000 - 2020-2040",
                                                  "1970-2000 - 2040-2060",
                                                  "1970-2000 - 2060-2080",
                                                  "1970-2000 - 2080-2100")) %>% 
                setNames(models[m])
        
        }) %>% 
        do.call(c, .) %>%
        merge() %>% 
        
        st_apply(c("x", "y", "attributes"), mean) %>% 
        
        {
            ggplot() +
                geom_stars(data = .) +
                geom_sf(data = belem, fill = NA) +
                facet_wrap(~attributes, nrow = 1) +
                scale_fill_distiller(name = NULL, palette = "Spectral", direction = -1) +
                scale_x_continuous(breaks = c(-48.7, -48.2)) +
                scale_y_continuous(breaks = c(-1.6, -1)) +
                labs(title = biovars[i]) +
                theme(axis.title = element_blank())
        }
}

```

```{r}

func_plot(1)

```

```{r}

func_plot(2)

```

```{r}

func_plot(3)

```

```{r}

func_plot(4)

```

```{r}

func_plot(5)

```

```{r}

func_plot(6)

```

```{r}

func_plot(7)

```

```{r}

func_plot(8)

```

```{r}

func_plot(9)

```

```{r}

func_plot(10)

```

```{r}

func_plot(11)

```

```{r}

func_plot(12)

```

```{r}

func_plot(13)

```

```{r}

func_plot(14)

```

```{r}

func_plot(15)

```

```{r}

func_plot(16)

```

```{r}

func_plot(17)

```

```{r}

func_plot(18)

```

```{r}

func_plot(19)

```
