---
title: "Preliminary analysis"
author: "Carlos Dobler"
date: "October 17, 2021"
output: html_document
knit: (function(input_file, encoding) {
      rmarkdown::render(input_file,
                        encoding = encoding, 
                        output_dir = here::here("output"))})
---

```{r, setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      out.width = "90%",
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 7.5, 
                      fig.asp = 0.4, 
                      dpi = 150)


library(tidyverse)
library(stars)
library(rnaturalearth)

# constants
x_min <- 3150L
y_min <- 2182L
x_count <- 16L
y_count <- 20L

biovars <- c(
    "Δ Annual Mean Temperature",
    "Δ Mean Diurnal Range",
    "Δ Isothermality",
    "Δ Temperature Seasonality",
    "Δ Max Temperature of Warmest Month",
    "Δ Min Temperature of Coldest Month",
    "Δ Temperature Annual Range",
    "Δ Mean Temperature of Wettest Quarter",
    "Δ Mean Temperature of Driest Quarter",
    "Δ Mean Temperature of Warmest Quarter",
    "Δ Mean Temperature of Coldest Quarter",
    "Δ Annual Precipitation",
    "Δ Precipitation of Wettest Month",
    "Δ Precipitation of Driest Month",
    "Δ Precipitation Seasonality (Coefficient of Variation)",
    "Δ Precipitation of Wettest Quarter",
    "Δ Precipitation of Driest Quarter",
    "Δ Precipitation of Warmest Quarter",
    "Δ Precipitation of Coldest Quarter")

models <- c("BCC-CSM2-MR",
            "CNRM-CM6-1",
            "CNRM-ESM2-1",
            "CanESM5",
            "IPSL-CM6A-LR",
            "MIROC-ES2L",
            "MIROC6")#,
            #"MRI-ESM2-0")

read_sf(here::here("data", "belem.gpkg")) -> belem
read_sf(here::here("data", "land.gpkg")) -> land

# hist
tibble(file = list.files(here::here("data/Link to WorldClim/historical_1970_2000/"), full.names = T),
       v = file %>% 
           str_sub(-6) %>% 
           str_replace("_", "") %>% 
           str_sub(end = -5) %>% 
           as.numeric()) %>% 
    
    arrange(v) %>% 
    pull(file) %>% 
    
    map(~read_stars(.x, RasterIO = list(nXOff = x_min,
                                   nYOff = y_min,
                                   nXSize = x_count,
                                   nYSize = y_count))) %>% 
    do.call(c, .) %>%
    merge() %>% 
    st_set_dimensions(3, biovars) %>% 
    setNames("p_1970_2000") -> miau_c1

# future
seq_along(models) %>% 
    map(function(m){
        
        list.files(here::here("data/Link to WorldClim/future_2021_2100_ssp585/"), full.names = T) %>%
            .[str_detect(., "tif")] %>% 
            .[str_detect(., models[m])] %>% 
            
            map(~read_stars(.x, RasterIO = list(nXOff = x_min,
                                                nYOff = y_min,
                                                nXSize = x_count,
                                                nYSize = y_count)) %>% 
                    st_as_stars()) %>% 
            do.call(c, .) %>% 
            st_set_dimensions("band", names = "attributes", values = biovars) %>% 
            setNames(c("p_2020_2040", "p_2040_2060", "p_2060_2080", "p_2080_2100"))
            
    }) -> miau_c2

# db %>% slice(attributes, 1) %>% select(1) %>% {ggplot() + geom_stars(data = .) + geom_sf(data = belem)}

func_plot <- function(i)
{
    
    seq_along(models) %>%
        map(function(m){
            
            db <- c(miau_c1, miau_c2[[m]])
            
            db %>% 
                slice(attributes, i) %>% 
                mutate(a = p_2020_2040 - p_1970_2000,
                       b = p_2040_2060 - p_1970_2000,
                       c = p_2060_2080 - p_1970_2000,
                       d = p_2080_2100 - p_1970_2000) %>% 
                select(a:d) %>% 
                merge() %>% 
                st_set_dimensions("attributes", c("1970-2000 - 2020-2040",
                                                  "1970-2000 - 2040-2060",
                                                  "1970-2000 - 2060-2080",
                                                  "1970-2000 - 2080-2100")) %>% 
                setNames(models[m])
        
        }) %>% 
        do.call(c, .) %>%
        merge() %>% 
        
        st_apply(c("x", "y", "attributes"), mean) %>% 
        
        {
            ggplot() +
                geom_stars(data = .) +
                geom_sf(data = land, fill = NA) +
                geom_sf(data = belem, fill = NA, linetype = "dotted") +
                facet_wrap(~attributes, nrow = 1) +
                scale_fill_distiller(name = NULL, palette = "Spectral", direction = -1) +
                scale_x_continuous(breaks = c(-48.7, -48.2)) +
                scale_y_continuous(breaks = c(-1.6, -1)) +
                labs(title = biovars[i]) +
                theme(axis.title = element_blank()) +
                # coord_sf(xlim = c(-49, -47), ylim = c(-2, 0))
                coord_sf(ylim = c(st_get_dimension_values(., "y") %>% last(),
                                  st_get_dimension_values(., "y") %>% first()),
                         xlim = c(st_get_dimension_values(., "x") %>% first(),
                                  st_get_dimension_values(., "x") %>% last()))
                
        }
}

```

## WorldClim's bioclimatic variables (2.5 min)

```{r}

func_plot(1)

```

```{r}

func_plot(2)

```

```{r}

func_plot(3)

```

```{r}

func_plot(4)

```

```{r}

func_plot(5)

```

```{r}

func_plot(6)

```

```{r}

func_plot(7)

```

```{r}

func_plot(8)

```

```{r}

func_plot(9)

```

```{r}

func_plot(10)

```

```{r}

func_plot(11)

```

```{r}

func_plot(12)

```

```{r}

func_plot(13)

```

```{r}

func_plot(14)

```

```{r}

func_plot(15)

```

```{r}

func_plot(16)

```

```{r}

func_plot(17)

```

```{r}

func_plot(18)

```

```{r}

func_plot(19)

```

### Examples of a larger extent

```{r}

tibble(file = list.files(here::here("data/Link to WorldClim/historical_1970_2000/"), full.names = T),
       v = file %>% 
           str_sub(-6) %>% 
           str_replace("_", "") %>% 
           str_sub(end = -5) %>% 
           as.numeric()) %>% 
    
    arrange(v) %>% 
    pull(file) %>% 
    
    map(~read_stars(.x, RasterIO = list(nXOff = x_min - 20,
                                        nYOff = y_min - 10,
                                        nXSize = x_count + 40,
                                        nYSize = y_count + 40))) %>% 
    do.call(c, .) %>%
    merge() %>% 
    st_set_dimensions(3, biovars) %>% 
    setNames("p_1970_2000") -> miau_c1_2

# future
seq_along(models) %>% 
    map(function(m){
        
        list.files(here::here("data/Link to WorldClim/future_2021_2100_ssp585/"), full.names = T) %>%
            .[str_detect(., "tif")] %>% 
            .[str_detect(., models[m])] %>% 
            
            map(~read_stars(.x, RasterIO = list(nXOff = x_min - 20,
                                                nYOff = y_min - 10,
                                                nXSize = x_count + 40,
                                                nYSize = y_count + 40)) %>% 
                    st_as_stars()) %>% 
            do.call(c, .) %>% 
            st_set_dimensions("band", names = "attributes", values = biovars) %>% 
            setNames(c("p_2020_2040", "p_2040_2060", "p_2060_2080", "p_2080_2100"))
            
    }) -> miau_c2_2

seq_along(models) %>%
    map(function(m){
        
        db <- c(miau_c1_2, miau_c2_2[[m]])
        
        db %>% 
            slice(attributes, 7) %>% 
            mutate(a = p_2020_2040 - p_1970_2000,
                   b = p_2040_2060 - p_1970_2000,
                   c = p_2060_2080 - p_1970_2000,
                   d = p_2080_2100 - p_1970_2000) %>% 
            select(a:d) %>% 
            merge() %>% 
            st_set_dimensions("attributes", c("1970-2000 - 2020-2040",
                                              "1970-2000 - 2040-2060",
                                              "1970-2000 - 2060-2080",
                                              "1970-2000 - 2080-2100")) %>% 
            setNames(models[m])
        
    }) %>% 
    do.call(c, .) %>%
    merge() %>% 
    
    st_apply(c("x", "y", "attributes"), mean) %>% 
    
    {
        ggplot() +
            geom_stars(data = .) +
            geom_sf(data = land, fill = NA) +
            geom_sf(data = belem, fill = NA, linetype = "dotted") +
            facet_wrap(~attributes, nrow = 1) +
            scale_fill_distiller(name = NULL, palette = "Spectral", direction = -1) +
            scale_x_continuous(breaks = c(-49, -48)) +
            scale_y_continuous(breaks = c(-2, -1)) +
            labs(title = biovars[7]) +
            theme(axis.title = element_blank()) +
            # coord_sf(xlim = c(-49, -47), ylim = c(-2, 0))
            coord_sf(ylim = c(st_get_dimension_values(., "y") %>% last(),
                              st_get_dimension_values(., "y") %>% first()),
                     xlim = c(st_get_dimension_values(., "x") %>% first(),
                              st_get_dimension_values(., "x") %>% last()))
        
    }

```

```{r}

seq_along(models) %>%
    map(function(m){
        
        db <- c(miau_c1_2, miau_c2_2[[m]])
        
        db %>% 
            slice(attributes, 18) %>% 
            mutate(a = p_2020_2040 - p_1970_2000,
                   b = p_2040_2060 - p_1970_2000,
                   c = p_2060_2080 - p_1970_2000,
                   d = p_2080_2100 - p_1970_2000) %>% 
            select(a:d) %>% 
            merge() %>% 
            st_set_dimensions("attributes", c("1970-2000 - 2020-2040",
                                              "1970-2000 - 2040-2060",
                                              "1970-2000 - 2060-2080",
                                              "1970-2000 - 2080-2100")) %>% 
            setNames(models[m])
        
    }) %>% 
    do.call(c, .) %>%
    merge() %>% 
    
    st_apply(c("x", "y", "attributes"), mean) %>% 
    
    {
        ggplot() +
            geom_stars(data = .) +
            geom_sf(data = land, fill = NA) +
            geom_sf(data = belem, fill = NA, linetype = "dotted") +
            facet_wrap(~attributes, nrow = 1) +
            scale_fill_distiller(name = NULL, palette = "Spectral", direction = -1) +
            scale_x_continuous(breaks = c(-49, -48)) +
            scale_y_continuous(breaks = c(-2, -1)) +
            labs(title = biovars[18]) +
            theme(axis.title = element_blank()) +
            # coord_sf(xlim = c(-49, -47), ylim = c(-2, 0))
            coord_sf(ylim = c(st_get_dimension_values(., "y") %>% last(),
                              st_get_dimension_values(., "y") %>% first()),
                     xlim = c(st_get_dimension_values(., "x") %>% first(),
                              st_get_dimension_values(., "x") %>% last()))
        
    }

```


## REMO precip

```{r}

library(lubridate)

mod <- "had"

readRDS(here::here("data", str_glue("precip_{mod}_wdates.rds"))) %>% 
  st_apply(3, mean) %>%
  setNames("precip") %>% 
  as_tibble() %>% 
  mutate(precip = precip * 86400) -> precip_ts_daily

# ** R95p: Annual total precipitation from days > 95th percentile
precip_ts_daily %>%
  group_by(year = year(time)) %>% 
  mutate(precip = ifelse(precip >= quantile(precip, 0.95), precip, NA)) %>%
  summarize(precip = sum(precip, na.rm = T)) %>% 
  ungroup() %>% 
  
  ggplot(aes(x = year, y = precip)) +
  geom_smooth(color = "red") +
  geom_point() +
  labs(subtitle = "Annual total precip. from days > 95th percentile",
       y = "mm")

```

```{r}

# ** CWD: Maximum number of consecutive days with precip. ≥ 1mm
precip_ts_daily %>% 
  mutate(precip = ifelse(precip >= 1, 1, 0)) %>% 
  group_by(year = year(time)) %>%
  nest() %>% #{.$data[[1]]}
  mutate(cwd = map(data, function(x){
    
    tibble(l = rle(x$precip)$lengths,
           v = rle(x$precip)$values) %>% 
      filter(v == 1) %>% 
      pull(l) %>% 
      max()
    
  })) %>% 
  select(-data) %>% 
  unnest(cwd) %>% 
  
  ggplot(aes(x = year, y = cwd)) +
  geom_smooth(color = "red") +
  geom_point() +
  labs(subtitle = "Maximum number of consecutive days with precip. > 1 mm.",
       y = "no. of days")

```

```{r}

# ** CDD: Maximum number of consecutive days with precip. < 1mm
precip_ts_daily %>% 
  mutate(precip = ifelse(precip < 1, 1, 0)) %>% 
  group_by(year = year(time)) %>%
  nest() %>% #{.$data[[1]]}
  mutate(cwd = map(data, function(x){
    
    tibble(l = rle(x$precip)$lengths,
           v = rle(x$precip)$values) %>% 
      filter(v == 1) %>% 
      pull(l) %>% 
      max()
    
  })) %>% 
  select(-data) %>% 
  unnest(cwd) %>% 
  
  ggplot(aes(x = year, y = cwd)) +
  geom_smooth(color = "red") +
  geom_point() +
  labs(subtitle = "Maximum number of consecutive days with precip. < 1 mm.",
       y = "no. of days")

```

